In [1]:
import numpy as np
import time
import pandas as pd 
from sklearn.pipeline import Pipeline
from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d


In [5]:
##3 values - new
full_R = np.load("../data/c_a/processed/R_dataset_full.npz", allow_pickle=True)
X_full_R  = full_R["X"]
K0_full_R = full_R["K0"]

##3 values - new
full_R_477 = np.load("../data/c_a/processed/R_dataset_full_477.npz", allow_pickle=True)
X_full_R_477  = full_R_477["X"]
K0_full_R_477 = full_R_477["K0"]

ff = np.load("../data/c_a/processed/dataset_477.npz", allow_pickle=True)
xx  = full_R_477["X"]
k0 = full_R_477["K0"]

##git
full_477 = np.load("../data/c_a/processed/dataset_full_k477.npz", allow_pickle=True)
X_full_477  = full_477["X"]
K0_full_477 = full_477["K0"]

In [3]:
X_full_477

array([[ 16356., 102640., 247000., ...,  10598.,   5632.,   3072.],
       [ 16363., 102561., 246614., ...,   9861.,   5829.,   2982.],
       [ 16393., 102763., 247122., ...,  10346.,   5987.,   2838.],
       ...,
       [ 16356., 102612., 246888., ...,  14160.,   4104.,   6200.],
       [ 16332., 102349., 246076., ...,  13187.,   4204.,   5804.],
       [ 16352., 102583., 246812., ...,  13907.,   4288.,   6710.]],
      shape=(478084, 31))

In [4]:
X_full_R_477

array([[1.63560e+04, 1.07144e+05, 1.17887e+00],
       [1.63630e+04, 1.06944e+05, 1.17887e+00],
       [1.63930e+04, 1.07168e+05, 1.17887e+00],
       ...,
       [1.63320e+04, 1.06706e+05, 1.17887e+00],
       [1.63520e+04, 1.07054e+05, 1.17887e+00],
       [1.63110e+04, 1.06832e+05, 1.17887e+00]], shape=(119522, 3))

In [6]:
xx

array([[1.63560e+04, 1.07144e+05, 1.17887e+00],
       [1.63630e+04, 1.06944e+05, 1.17887e+00],
       [1.63930e+04, 1.07168e+05, 1.17887e+00],
       ...,
       [1.63320e+04, 1.06706e+05, 1.17887e+00],
       [1.63520e+04, 1.07054e+05, 1.17887e+00],
       [1.63110e+04, 1.06832e+05, 1.17887e+00]], shape=(119522, 3))